services:
  - type: web
    name: prontuai-backend
    runtime: python
    env: python
    region: oregon
    plan: free
    branch: v1
    rootDir: back-end
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && pip install email-validator"
    startCommand: "gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: BRMED_USERNAME
        sync: false
      - key: BRMED_PASSWORD
        sync: false
      - key: USE_TEXTRACT
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_HOURS
        value: 24
      - key: DATABASE_URL
        sync: false
